[package]
name = "spelsylt4"
version = "0.1.0"
edition = "2024"
default-run = "spelsylt4"

[dependencies]
accesskit = "0.21.1"
bevy_simple_text_input = "0.12.0"
serde = "1.0.228"
serde_json = "1.0.146"

[dependencies.bevy]
version = "0.17.3"
features = ["experimental_bevy_feathers"]
